// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEJIKPDu4jxea80f0YWRdJTqa343AObGI',
    appId: '1:328147837496:web:b8da5186dbb5df0d3cfccd',
    messagingSenderId: '328147837496',
    projectId: 'boreal-8cd7c',
    authDomain: 'boreal-8cd7c.firebaseapp.com',
    storageBucket: 'boreal-8cd7c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI6eCJKu0OP9E8SUGYvlVQr1ArW3t5kwM',
    appId: '1:328147837496:android:5c6a24aa83327f923cfccd',
    messagingSenderId: '328147837496',
    projectId: 'boreal-8cd7c',
    storageBucket: 'boreal-8cd7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpfHlqjlC0qoe7GY2easPoUfpiylfphqA',
    appId: '1:328147837496:ios:aa725c3badc08b1f3cfccd',
    messagingSenderId: '328147837496',
    projectId: 'boreal-8cd7c',
    storageBucket: 'boreal-8cd7c.firebasestorage.app',
    iosBundleId: 'com.example.constructionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpfHlqjlC0qoe7GY2easPoUfpiylfphqA',
    appId: '1:328147837496:ios:aa725c3badc08b1f3cfccd',
    messagingSenderId: '328147837496',
    projectId: 'boreal-8cd7c',
    storageBucket: 'boreal-8cd7c.firebasestorage.app',
    iosBundleId: 'com.example.constructionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEJIKPDu4jxea80f0YWRdJTqa343AObGI',
    appId: '1:328147837496:web:857a3d5ed38d58233cfccd',
    messagingSenderId: '328147837496',
    projectId: 'boreal-8cd7c',
    authDomain: 'boreal-8cd7c.firebaseapp.com',
    storageBucket: 'boreal-8cd7c.firebasestorage.app',
  );
}
